# -*- coding: utf-8 -*-

Exercise_Types = ["UB Hor Push", "UB Vert Push",  "UB Hor Pull", "UB Vert Pull",  "Hinge", "Squat", "LB Uni Push", 
"Ant Chain", "Post Chain",  "Isolation", "Iso 2", "Iso 3", "Iso 4", "RFL Load", "RFD Unload 1", "RFD Unload 2", "Carry"]

# DB_RDL_1 = "<p>The hinge movement pattern is one of the most important to perform to develop total body strength. A common variation of the hinge is the Romanian deadlift, or RDL. The RDL involves flexion and extension of the hips, beginning with the lifter standing fully upright, flexing the hips back or 'hinging' until the torso is nearly parallel to the ground, and extending the hips to return upright again. The primary muscles groups involved include the gluteals, hamstrings, quadriceps, spinal erectors, latissimus dorsi, and the forearms/hands.</p>"


Description_Dict = {}
Description_Dict["Hinge"] = {}
Description_Dict["Hinge"]["DB RDL"] = '<p>The hinge movement pattern is one of the most important to perform to develop total body strength. A common variation of the hinge is the Romanian deadlift, or RDL. The RDL involves flexion and extension of the hips, beginning with the lifter standing fully upright, flexing the hips back or “hinging” until the torso is nearly parallel to the ground, and extending the hips to return upright again. The primary muscles groups involved include the gluteals, hamstrings, quadriceps, spinal erectors, latissimus dorsi, and the forearms/hands.</p><ul><li>Stance: the stance used for a typical hinge pattern is a "power stance", directly under the hips. An easy way to find the proper stance is to close your eyes and take a small hop; your feet should land directly where they need to be. It is important to never “lock” the knees out, and instead keep them “soft” but strong.</li><li>Grip: Alloy Strength recommends using a double overhand grip for DB RDL, with the dumbbells sliding across the front of the thighs and maintaining contact. Some people prefer to have a neutral grip with the dumbbells on the sides of the body, but this can often create faulty mechanics where the lifter attempts to “squat” the weight, and bend at the knee instead.</li><li>Neutral spine: coaches often use the terms “flat back” or “table top back” to describe spinal positioning. However, this is incorrect as the spine is not truly flat. Every person’s spine has some degree of flexion, or rounding, in the upper back (thoracic region), and some degree of extension, or arching, in the lower back (lumbar region). While the exact degree of flexion and extension varies, and every person’s neutral spine may be a little bit different, a neutral spine is the guaranteed safest posture regardless of movement pattern or body positioning. It is very important to maintain a neutral spine throughout the entire hinge movement to help reduce risk of injury and improve performance.</li></ul><p>Hamstring flexibility and the ability to maintain a neutral spine determine ultimate range of motion for an RDL. The goal of an RDL is to maximize the true hinge capability of the hips, and maintain a vertical shin with minimum flexion or extension of the knee. Once the hamstrings reach terminal length, to move any farther we would either have to bend at the knee or lose a neutral spine. Neither is ideal, and so once the hamstrings are “tight” the lifter should return to an upright position. Proper movement quality will improve range of motion over time.</p>'
Description_Dict["Hinge"]["BB RDL"] = '<p>The hinge movement pattern is one of the most important to perform to develop total body strength. A common variation of the hinge is the Romanian deadlift, or RDL. The RDL involves flexion and extension of the hips, beginning with the lifter standing fully upright, flexing the hips back or “hinging” until the torso is nearly parallel to the ground, and extending the hips to return upright again. The primary muscles groups involved include the gluteals, hamstrings, quadriceps, spinal erectors, latissimus dorsi, and the forearms/hands.</p><ul><li>Stance: the stance used for a typical hinge pattern is a "power stance", directly under the hips. An easy way to find the proper stance is to close your eyes and take a small hop; your feet should land directly where they need to be. It is important to never “lock” the knees out, and instead keep them “soft” but strong.</li><li>Grip: Alloy Strength recommends using a double overhand grip for RDL, with the bar sliding across the front of the thighs and maintaining contact. The hands should be placed directly below the shoulder.</li></ul><p>Hamstring flexibility and the ability to maintain a neutral spine determine ultimate range of motion for an RDL. The goal of an RDL is to maximize the true hinge capability of the hips, and maintain a vertical shin with minimum flexion or extension of the knee. Proper movement quality will improve range of motion over time.</p>'
