# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-18 21:35
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('New_Code', models.CharField(default='', max_length=20)),
                ('Code', models.CharField(default='', max_length=20)),
                ('Name', models.CharField(default='', max_length=200)),
                ('Type', models.CharField(default='', max_length=200)),
                ('Level', models.IntegerField(default=0)),
                ('Bodyweight', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Level', models.IntegerField(default=0)),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sets', models.IntegerField(default=0)),
                ('Code', models.CharField(default='', max_length=2)),
                ('Exercise_Type', models.CharField(default='', max_length=200)),
                ('Level', models.IntegerField(default=0)),
                ('Reps', models.IntegerField(default=0)),
                ('Rest_Time', models.DurationField(default=datetime.timedelta(0, 120))),
                ('Order', models.IntegerField(default=0)),
                ('Exercise', models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.Exercise')),
            ],
        ),
        migrations.CreateModel(
            name='SubWorkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Exercise_Type', models.CharField(default='', max_length=200)),
                ('Sets', models.IntegerField(default=0)),
                ('Reps', models.IntegerField(default=0)),
                ('Order', models.IntegerField(default=0)),
                ('RPE', models.CharField(default='', max_length=3)),
                ('Deload', models.IntegerField(default=0)),
                ('Money', models.IntegerField(default=0)),
                ('Exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.Exercise')),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Level', models.IntegerField(default=0)),
                ('Ordered_ID', models.IntegerField(default=0)),
                ('Week', models.IntegerField(default=0)),
                ('Day', models.IntegerField(default=0)),
                ('Date', models.DateField(auto_now=True)),
                ('_Date', models.CharField(default='', max_length=10)),
                ('Sets', models.ManyToManyField(blank=True, default='', null=True, to='Users.Set')),
                ('SubWorkouts', models.ManyToManyField(default='', to='Users.SubWorkout')),
            ],
        ),
        migrations.CreateModel(
            name='Workout_Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Level_Group', models.IntegerField(default=0)),
                ('Level', models.IntegerField(default=0)),
                ('Ordered_ID', models.IntegerField(default=0)),
                ('Week', models.IntegerField(default=0)),
                ('Day', models.IntegerField(default=0)),
                ('_Date', models.CharField(default='', max_length=10)),
                ('SubWorkouts', models.ManyToManyField(default='', to='Users.SubWorkout')),
            ],
        ),
        migrations.AddField(
            model_name='workout',
            name='Template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.Workout_Template'),
        ),
    ]
