# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-02 16:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='Video',
        ),
    ]
