# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-02 16:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(default='', max_length=200)),
                ('Exercise_Name', models.CharField(default='', max_length=200)),
                ('Max', models.IntegerField(default=0)),
                ('Suggested_Weight', models.IntegerField(default=0)),
                ('Alloy_Weight', models.IntegerField(default=0)),
                ('Updated', models.BooleanField(default=False)),
                ('Alloy_Reps', models.IntegerField(default=0)),
                ('Alloy_Performance_Reps', models.IntegerField(default=0)),
                ('Level_Up', models.BooleanField(default=False)),
                ('Core', models.BooleanField(default=True)),
                ('Level', models.IntegerField(default=0)),
                ('Failed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SubWorkout_Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Exercise_Type', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('Sets', models.IntegerField(default=0)),
                ('Reps', models.CharField(default='', max_length=10)),
                ('Stop_Set', models.BooleanField(default=False)),
                ('Drop_Set', models.BooleanField(default=False)),
                ('Strength_Stop', models.IntegerField(default=0)),
                ('Strength_Drop', models.IntegerField(default=0)),
                ('Special_Reps', models.CharField(default='', max_length=10)),
                ('Order', models.IntegerField(default=0)),
                ('RPE', models.CharField(default='', max_length=3)),
                ('Deload', models.IntegerField(default=0)),
                ('Alloy', models.BooleanField(default=False)),
                ('Alloy_Reps', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tags', models.CharField(default='', max_length=300)),
                ('Title', models.CharField(default='', max_length=200)),
                ('File', models.FileField(upload_to='static/videos/')),
                ('Has_Thumbnail', models.BooleanField(default=False)),
                ('Thumbnail', models.FileField(default=None, upload_to='Thumbnails')),
                ('Exercise_Type', models.CharField(default='', max_length=200)),
                ('Description', models.CharField(default='', max_length=1000)),
                ('Default_Thumbnail_URL', models.CharField(default='/static/videos/Thumbnails/Default_Thumbnail.png', max_length=100)),
                ('Level_Access', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='subworkout',
            name='Deload',
        ),
        migrations.RemoveField(
            model_name='subworkout',
            name='Exercise_Type',
        ),
        migrations.RemoveField(
            model_name='subworkout',
            name='Money',
        ),
        migrations.RemoveField(
            model_name='subworkout',
            name='Order',
        ),
        migrations.RemoveField(
            model_name='subworkout',
            name='RPE',
        ),
        migrations.RemoveField(
            model_name='subworkout',
            name='Reps',
        ),
        migrations.RemoveField(
            model_name='subworkout',
            name='Sets',
        ),
        migrations.AddField(
            model_name='exercise',
            name='Description_Code',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='exercise',
            name='Pause',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='exercise',
            name='Tempo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exercise',
            name='Tempo_Value',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='exercise',
            name='Video_Description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='member',
            name='Admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='Agreed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='Bench',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='CJerk',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='member',
            name='DOB',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='member',
            name='D_Lift',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='member',
            name='Expiry_Date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='Finished_Workouts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='Has_Workouts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='Height',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='member',
            name='New',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='member',
            name='OP',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='member',
            name='Other',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='member',
            name='PC',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='member',
            name='Paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='Picture',
            field=models.FileField(default='', upload_to='static/user_profile_pictures'),
        ),
        migrations.AddField(
            model_name='member',
            name='Primary_Sports',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='member',
            name='Prior_RPE',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='Read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='Signup_Date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='Snatch',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='member',
            name='Squat',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='Training_Time',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='member',
            name='Weight',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='subworkout',
            name='Alloy_Passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subworkout',
            name='Alloy_Weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subworkout',
            name='Drop_Sets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subworkout',
            name='Drop_Weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subworkout',
            name='Dropped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subworkout',
            name='Filled_Sets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subworkout',
            name='Maxed_Sets',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subworkout',
            name='Set_Stats',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='subworkout',
            name='Show_Alloy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subworkout',
            name='Special_Sets',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subworkout',
            name='Stop_Sets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subworkout',
            name='Stopped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subworkout',
            name='Submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subworkout',
            name='Suggested_Weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workout',
            name='Alloy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workout',
            name='Alloy_Passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workout',
            name='Completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workout',
            name='Current_Block',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='Last_Alloy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workout',
            name='Last_Workout',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workout',
            name='Member',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='Users.Member'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workout',
            name='Show_Alloy_Weights',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workout',
            name='Submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workout_template',
            name='Alloy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workout_template',
            name='Block',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='workout_template',
            name='Block_End',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workout_template',
            name='Block_Num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workout_template',
            name='First',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workout_template',
            name='Has_Tempo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workout_template',
            name='Last',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='Level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='workout_template',
            name='SubWorkouts',
            field=models.ManyToManyField(default='', to='Users.SubWorkout_Template'),
        ),
        migrations.AddField(
            model_name='video',
            name='Exercises',
            field=models.ManyToManyField(default='', related_name='Video', to='Users.Exercise'),
        ),
        migrations.AddField(
            model_name='stat',
            name='Member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Stats', to='Users.Member'),
        ),
        migrations.AddField(
            model_name='subworkout',
            name='Template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.SubWorkout_Template'),
        ),
    ]
