# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-18 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20170818_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='Code',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='exercise',
            name='New_Code',
            field=models.CharField(default='', max_length=20),
        ),
    ]
