# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-11 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_auto_20170911_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tags', models.CharField(default='', max_length=300)),
                ('Title', models.CharField(default='', max_length=200)),
                ('File', models.FileField(upload_to='static/videos/')),
                ('Thumbnail', models.FileField(upload_to='static/videos/Thumbnails')),
                ('Exercise_Type', models.CharField(default='', max_length=200)),
                ('Description', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
