# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-11 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='Member',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='Users.Member'),
            preserve_default=False,
        ),
    ]
