# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-13 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_auto_20170913_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='max',
            name='Alloy_Reps',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='max',
            name='Level_Up',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subworkout',
            name='Alloy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subworkout',
            name='Alloy_Reps',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workout',
            name='Alloy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workout',
            name='Last_Alloy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workout',
            name='Last_Workout',
            field=models.BooleanField(default=False),
        ),
    ]
