# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-13 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_auto_20170913_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout_template',
            name='Alloy',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subworkout',
            name='Set_Stats',
            field=models.CharField(default=',,/,,/,,/,,', max_length=300),
        ),
    ]
