# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-13 08:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_auto_20170913_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='Video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='Users.Video'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='Video_Description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
