# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-16 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0011_auto_20170913_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subworkout',
            name='Money',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
