# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-16 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0012_auto_20170916_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout_template',
            name='First',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workout_template',
            name='Last',
            field=models.BooleanField(default=False),
        ),
    ]
