# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-16 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0013_auto_20170916_0743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(default='', max_length=200)),
                ('Exercise_Name', models.CharField(default='', max_length=200)),
                ('Max', models.IntegerField(default=0)),
                ('Updated', models.BooleanField(default=False)),
                ('Alloy_Reps', models.IntegerField(default=0)),
                ('Level_Up', models.BooleanField(default=False)),
                ('Member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Stats', to='Users.Member')),
            ],
        ),
        migrations.RemoveField(
            model_name='max',
            name='Member',
        ),
        migrations.DeleteModel(
            name='Max',
        ),
    ]
