# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-16 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0014_auto_20170916_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='Core',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stat',
            name='Level',
            field=models.IntegerField(default=0),
        ),
    ]
