# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-16 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0015_auto_20170916_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='Failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stat',
            name='Core',
            field=models.BooleanField(default=True),
        ),
    ]
