# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-16 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0016_auto_20170916_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='Tempo',
            field=models.BooleanField(default=False),
        ),
    ]
