# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-16 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0019_auto_20170916_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='Alloy_Weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subworkout',
            name='Set_Stats',
            field=models.CharField(default='', max_length=300),
        ),
    ]
