# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-16 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0021_stat_suggested_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='subworkout',
            name='Alloy_Revealed',
            field=models.BooleanField(default=False),
        ),
    ]
