# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-17 08:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0022_subworkout_alloy_revealed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subworkout',
            old_name='Alloy_Revealed',
            new_name='Show_Alloy',
        ),
    ]
