# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-17 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0025_stat_alloy_performance_reps'),
    ]

    operations = [
        migrations.AddField(
            model_name='subworkout',
            name='Filled_Sets',
            field=models.IntegerField(default=0),
        ),
    ]
