# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-18 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0026_subworkout_filled_sets'),
    ]

    operations = [
        migrations.AddField(
            model_name='subworkout',
            name='Alloy_Passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subworkout',
            name='Submitted',
            field=models.BooleanField(default=False),
        ),
    ]
