# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-18 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0027_auto_20170918_0333'),
    ]

    operations = [
        migrations.AddField(
            model_name='subworkout',
            name='Special_Reps',
            field=models.CharField(default='', max_length=10),
        ),
    ]
