# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-18 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0028_subworkout_special_reps'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='Description_Code',
            field=models.CharField(default='', max_length=20),
        ),
    ]
