# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-18 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0030_auto_20170918_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='Has_Workout',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='New',
            field=models.BooleanField(default=True),
        ),
    ]
