# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-18 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0031_auto_20170918_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='Current_Block',
            field=models.BooleanField(default=True),
        ),
    ]
