# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-18 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0034_auto_20170918_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='Admin',
            field=models.BooleanField(default=False),
        ),
    ]
