# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-18 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0035_member_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='Expiry_Date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='Paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='Signup_Date',
            field=models.DateTimeField(null=True),
        ),
    ]
