# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-23 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0036_auto_20170918_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subworkout',
            name='Reps',
            field=models.CharField(default='', max_length=4),
        ),
    ]
