# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-24 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0038_auto_20170924_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='subworkout',
            name='Suggested_Weight',
            field=models.IntegerField(default=0),
        ),
    ]
