# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-24 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0039_subworkout_suggested_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='subworkout',
            name='Maxed_Sets',
            field=models.BooleanField(default=False),
        ),
    ]
