# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-24 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0040_subworkout_maxed_sets'),
    ]

    operations = [
        migrations.AddField(
            model_name='subworkout',
            name='Drop_Set',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subworkout',
            name='Stop_Set',
            field=models.BooleanField(default=False),
        ),
    ]
