# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-24 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0041_auto_20170924_0850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subworkout',
            name='Alloy',
        ),
        migrations.RemoveField(
            model_name='subworkout',
            name='Alloy_Reps',
        ),
        migrations.RemoveField(
            model_name='subworkout',
            name='Deload',
        ),
        migrations.RemoveField(
            model_name='subworkout',
            name='Drop_Set',
        ),
        migrations.RemoveField(
            model_name='subworkout',
            name='Exercise',
        ),
        migrations.RemoveField(
            model_name='subworkout',
            name='Exercise_Type',
        ),
        migrations.RemoveField(
            model_name='subworkout',
            name='Money',
        ),
        migrations.RemoveField(
            model_name='subworkout',
            name='Order',
        ),
        migrations.RemoveField(
            model_name='subworkout',
            name='RPE',
        ),
        migrations.RemoveField(
            model_name='subworkout',
            name='Reps',
        ),
        migrations.RemoveField(
            model_name='subworkout',
            name='Set_1',
        ),
        migrations.RemoveField(
            model_name='subworkout',
            name='Set_2',
        ),
        migrations.RemoveField(
            model_name='subworkout',
            name='Set_3',
        ),
        migrations.RemoveField(
            model_name='subworkout',
            name='Set_4',
        ),
        migrations.RemoveField(
            model_name='subworkout',
            name='Sets',
        ),
        migrations.RemoveField(
            model_name='subworkout',
            name='Special_Reps',
        ),
        migrations.RemoveField(
            model_name='subworkout',
            name='Stop_Set',
        ),
        migrations.RemoveField(
            model_name='subworkout',
            name='Strength_Drop',
        ),
        migrations.RemoveField(
            model_name='subworkout',
            name='Strength_Stop',
        ),
        migrations.AddField(
            model_name='subworkout_template',
            name='Alloy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subworkout_template',
            name='Alloy_Reps',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subworkout_template',
            name='Drop_Set',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subworkout_template',
            name='Special_Reps',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='subworkout_template',
            name='Stop_Set',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subworkout_template',
            name='Strength_Drop',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subworkout_template',
            name='Strength_Stop',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subworkout_template',
            name='Exercise_Type',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subworkout_template',
            name='Money',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='subworkout_template',
            name='Reps',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='workout_template',
            name='SubWorkouts',
            field=models.ManyToManyField(default='', to='Users.SubWorkout_Template'),
        ),
    ]
