# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-24 10:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0042_auto_20170924_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subworkout_template',
            name='Money',
        ),
        migrations.AddField(
            model_name='subworkout',
            name='Template',
            field=models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.SubWorkout_Template'),
        ),
    ]
