# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-24 11:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0044_auto_20170924_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subworkout_template',
            name='Exercise',
        ),
        migrations.AddField(
            model_name='subworkout',
            name='Exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.Exercise'),
        ),
    ]
