# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-24 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0045_auto_20170924_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='subworkout',
            name='Drop_Sets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subworkout',
            name='Stop_Sets',
            field=models.IntegerField(default=0),
        ),
    ]
