# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-24 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0046_auto_20170924_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='subworkout',
            name='Dropped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subworkout',
            name='Stopped',
            field=models.BooleanField(default=False),
        ),
    ]
