# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-24 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0048_subworkout_template_special_sets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subworkout_template',
            name='Special_Sets',
        ),
        migrations.AddField(
            model_name='subworkout',
            name='Special_Sets',
            field=models.BooleanField(default=False),
        ),
    ]
