# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-24 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0049_auto_20170924_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout_template',
            name='Has_Tempo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subworkout_template',
            name='Reps',
            field=models.CharField(default='', max_length=10),
        ),
    ]
