# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-24 22:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0050_auto_20170924_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='Has_Workout',
            new_name='Finished_Workouts',
        ),
    ]
