# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-24 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0051_auto_20170924_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout_template',
            name='Block_End',
            field=models.BooleanField(default=False),
        ),
    ]
