# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-26 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0053_video_level_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='Picture',
            field=models.FileField(default='', upload_to='static/user_profile_pictures'),
        ),
    ]
