# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-26 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0054_member_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='subworkout',
            name='Drop_Weight',
            field=models.IntegerField(default=0),
        ),
    ]
