# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-29 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0056_member_agreed'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='Has_Workouts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='Read',
            field=models.BooleanField(default=False),
        ),
    ]
