# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-30 19:33
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0057_auto_20170929_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('Date', models.DateTimeField(blank=True, null=True)),
                ('Images', models.ImageField(blank=True, upload_to=b'/Users/asitwala/AS_Final_2/AS_Final_2/AS_Final/media')),
            ],
        ),
    ]
