# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-30 22:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0058_blog_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_post',
            name='Images',
        ),
    ]
