# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-01 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0058_blog_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='Bench',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='CJerk',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='member',
            name='DOB',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='member',
            name='D_Lift',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='member',
            name='Height',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='member',
            name='OP',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='member',
            name='Other',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='member',
            name='PC',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='member',
            name='Primary_Sports',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='member',
            name='Prior_RPE',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='Snatch',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='member',
            name='Training_Time',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='member',
            name='Weight',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='member',
            name='Squat',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, null=True),
        ),
    ]
