# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-02 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0060_auto_20171002_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='Default_Thumbnail_URL',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='Thumbnail',
            field=models.FileField(default=None, upload_to='Thumbnails'),
        ),
    ]
