# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-02 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0061_auto_20171002_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='Default_Thumbnail_URL',
            field=models.CharField(default='/static/videos/Thumbnails/Default_Thumbnail.png', max_length=100),
        ),
    ]
