# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-02 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0063_video_has_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='Video',
        ),
        migrations.AddField(
            model_name='video',
            name='Exercises',
            field=models.ManyToManyField(default='', to='Users.Exercise'),
        ),
    ]
