# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-02 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0064_auto_20171002_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='Exercises',
            field=models.ManyToManyField(default='', related_name='Video', to='Users.Exercise'),
        ),
    ]
